### PR TITLE
Testing build under linux

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by wfspotz** [comment]
Hi @zonca. What is the motivation to switch to mpich?

**Comment by zonca** [comment]
I noticed mpi4py builds the conda package with mpich, so wanted to give it
a try. But still no success.

Il lun 29 gen 2018, 18:11 Bill Spotz <notifications@github.com> ha scritto:

**Comment by looooo** [comment]
```
-D MPI_CXX_LIBRARIES="${PREFIX}/lib/libmpi.so;${PREFIX}/lib/libmpi_cxx.so"
```
with another library I had to add this line to the cmake-config to get it compiled with mpich. maybe you have to do something similar.

**Comment by isuruf** [comment]
cc @conda-forge/mpi4py

**Comment by dalcinl** [comment]
In `build.sh`, simply remove this stuff (or somehow protect it to not set `MPI_FLAGS` in case of MPICH):

```
export MPI_FLAGS=--allow-run-as-root

if [ $(uname) == Linux ]; then
    export MPI_FLAGS="$MPI_FLAGS;-mca;plm;isolated"
fi
```

I would recommend as well to set these variables, this way in the near future you will be able to build with both MPICH and Open MPI. 

```
export HYDRA_LAUNCHER=fork
export OMPI_MCA_plm=isolated
export OMPI_MCA_btl_vader_single_copy_mechanism=none
export OMPI_MCA_rmaps_base_oversubscribe=yes
```

**Comment by zonca** [comment]
@wfspotz now with `mpich` the tests are passing, the anaconda upload for some reason is still failing, so I had to disable the check at https://github.com/conda-forge/pytrilinos-feedstock/pull/9/commits/8b4564cdc1c41ee73273909324845f4d3034c756

I think the problem was that the `mpi4py` conda package requires `mpich` so we had both openmpi and mpich installed.

**Comment by minrk** [comment]
Once https://github.com/conda-forge/staged-recipes/pull/1501 lands, openmpi and mpich will be able to be mutually exclusive. That's a prerequisite for the mpi4py package supporting both, which is [ready to go](https://github.com/conda-forge/mpi4py-feedstock/pull/10) as soon as the above mpi metapackage is merged.

**Comment by zonca** [comment]
@wfspotz what about merging this for now and see if the anaconda upload works in the master branch?

Then we can try switch back to openmpi once @minrk 's MPI metapackage is available.

**Pull request merged**
