### PR TITLE
Add support for Windows

### PR DESCRIPTION
**Pull request by wfspotz**

### CODE REVIEW

**Comment by isuruf** [comment]
You need to rerender the repo. See https://conda-forge.org/docs/conda_smithy.html#how-to-re-render

**Comment by isuruf** [comment]
Also, please use a fork instead of creating a branch on this repo. (Branches also upload the package to anaconda.org, which we don't want for this case. Also it wastes CI resources)

**Comment by wfspotz** [comment]
OK. When I tried to rerender, it said the feedstock was up to date:

    $ conda smithy rerender -c
    Fetching package metadata ...........
    Fetching package metadata ...........
    Fetching package metadata .............
    Fetching package metadata .............
    
    Re-rendered with conda-smithy 2.4.0.
    
    No changes made. This feedstock is up-to-date.

**Comment by isuruf** [comment]
Did you rerender in wfspotz/master or in conda-forge/master?

**Comment by wfspotz** [comment]
I rerendered in wfspotz/master.

**Comment by isuruf** [comment]
This PR should be closed in favour of #6

**Pull request closed without merging**
